name: faker_app_flutter_firebase
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: 1.0.8
  flutter_riverpod: 2.5.1
  go_router: 14.1.1
  equatable: 2.0.5
  firebase_core_web: ^2.17.0
  firebase_core: ^2.31.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 4.0.0

flutter:
  uses-material-design: true
